@secure()
param ACCESS_TOKEN_SECRET string
@secure()
param APPLICATIONINSIGHTS_CONNECTION_STRING string 
@secure()
param ApplicationInsightsAgent_EXTENSION_VERSION string
@secure()
param AZURE_ACCOUNT_KEY string 
@secure()
param AZURE_ACCOUNT_NAME string 
@secure()
param AZURE_STORAGE_CONTAINER string 
@secure()
param CHROME_TOKEN string 
@secure()
param CHROME_PORT string 
@secure()
param CHROME_URL string 
@secure()
param DATABASE_URL string 
@secure()
param DOCKER_ENABLE_CI string 
@secure()
param DOCKER_REGISTRY_SERVER_PASSWORD string 
@secure()
param DOCKER_REGISTRY_SERVER_USERNAME string 
@secure()
param DOCKER_REGISTRY_SERVER_URL string 
@secure()
param GITHUB_CALLBACK_URL string
@secure()
param GITHUB_CLIENT_ID string
@secure()
param GITHUB_CLIENT_SECRET string
@secure()
param GOOGLE_CALLBACK_URL string
@secure()
param GOOGLE_CLIENT_ID string
@secure()
param GOOGLE_CLIENT_SECRET string
@secure()
param MICROSOFT_AUTHORIZATION_URL string 
@secure()
param MICROSOFT_CALLBACK_URL string
@secure()
param MICROSOFT_CLIENT_ID string
@secure()
param MICROSOFT_CLIENT_SECRET string
@secure()
param MICROSOFT_SCOPE string
@secure()
param MICROSOFT_TOKEN_URL string 
@secure()
param MICROSOFT_USER_INFO_URL string
@secure()
param OPENAI_API_KEY string
@secure()
param POSTGRES_DB string
@secure()
param POSTGRES_PASSWORD string
@secure()
param POSTGRES_USER string
@secure()
param POSTGRES_PORT string
@secure()
param REFRESH_TOKEN_SECRET string
@secure()
param STORAGE_ACCESS_KEY string
@secure()
param STORAGE_BUCKET string
@secure()
param STORAGE_ENDPOINT string
@secure()
param STORAGE_PORT string
@secure()
param STORAGE_REGION string
@secure()
param STORAGE_SECRET_KEY string
@secure()
param STORAGE_SKIP_BUCKET_CHECK string
@secure()
param STORAGE_URL string
@secure()
param STORAGE_USE_SSL string
@secure()
param WEBSITES_ENABLE_APP_SERVICE_STORAGE string
@secure()
param XDT_MicrosoftApplicationInsights_Mode string

param location string = resourceGroup().location
param prefix string = 'ezcv'
@allowed([
  'latest'
  'beta'
  'prod'
])
param dockerTag string = 'latest'

param name string = '${prefix}-${dockerTag}-container-webapp'

resource serverFarm 'Microsoft.Web/serverfarms@2024-04-01' = {
  name: '${prefix}-ASP-${dockerTag}'
  location: location
  sku: {
    name: 'B3'
    tier: 'Basic'
    size: 'B3'
    family: 'B'
    capacity: 1
  }
  properties: {
    reserved: true
    perSiteScaling: false
    maximumElasticWorkerCount: 1
  }
}

resource sites 'Microsoft.Web/sites@2024-04-01' = {
  name: name
  location: location
  tags: {
    'hidden-link: /app-insights-resource-id': '/subscriptions/d3730832-4250-4e51-b454-680e31182cd4/resourceGroups/EzCV/providers/microsoft.insights/components/EzCV-webapp-2'
    'hidden-link: /app-insights-instrumentation-key': '330b0fb6-6ddd-4c0f-a588-718399c6d827'
    'hidden-link: /app-insights-conn-string': 'InstrumentationKey=330b0fb6-6ddd-4c0f-a588-718399c6d827;IngestionEndpoint=https://northeurope-2.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/;ApplicationId=5b1af7cd-49b5-4cdc-9157-29af8a11474d'
  }
  kind: 'app,linux,container'
  properties: {
    enabled: true
    serverFarmId: serverFarm.id
    reserved: true
    isXenon: false
    hyperV: false
    dnsConfiguration: {}
    vnetRouteAllEnabled: false
    vnetImagePullEnabled: false
    vnetContentShareEnabled: false
    siteConfig: {
      numberOfWorkers: 1
      linuxFxVersion: 'DOCKER|mfknudsen/ez-cv:${dockerTag}'
      acrUseManagedIdentityCreds: false
      alwaysOn: false
      http20Enabled: false
      functionAppScaleLimit: 0
      minimumElasticInstanceCount: 1
    }
    scmSiteAlsoStopped: false
    clientAffinityEnabled: false
    clientCertEnabled: false
    clientCertMode: 'Required'
    hostNamesDisabled: false
    ipMode: 'IPv4'
    vnetBackupRestoreEnabled: false
    customDomainVerificationId: '9B42C5BA2C3D4B566F0D11A198C4B9F5288000D33B9993E9988BE0D3AB475803'
    containerSize: 0
    dailyMemoryTimeQuota: 0
    httpsOnly: true
    endToEndEncryptionEnabled: false
    redundancyMode: 'None'
    publicNetworkAccess: 'Enabled'
    storageAccountRequired: false
    keyVaultReferenceIdentity: 'SystemAssigned'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

resource ftp 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2024-04-01' = {
  parent: sites
  name: 'ftp'
  properties: {
    allow: true
  }
}

resource scm 'Microsoft.Web/sites/basicPublishingCredentialsPolicies@2024-04-01' = {
  parent: sites
  name: 'scm'
  properties: {
    allow: true
  }
}

resource dockerApp 'Microsoft.Web/sites/config@2024-04-01' = {
  parent: sites
  name: 'web'
  properties: {
    appSettings: [
      {
        name: 'ACCESS_TOKEN_SECRET'
        value: ACCESS_TOKEN_SECRET
      }
      {
      name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
      value: APPLICATIONINSIGHTS_CONNECTION_STRING 
      }
      {
      name: 'ApplicationInsightsAgent_EXTENSION_VERSION'
      value: ApplicationInsightsAgent_EXTENSION_VERSION 
      }
      {
      name: 'AZURE_ACCOUNT_KEY'
      value: AZURE_ACCOUNT_KEY
      }
      {
      name: 'AZURE_ACCOUNT_NAME'
      value: AZURE_ACCOUNT_NAME
      }
      {
      name: 'AZURE_STORAGE_CONTAINER'
      value: AZURE_STORAGE_CONTAINER
      }
      {
      name: 'CHROME_TOKEN'
      value: CHROME_TOKEN
      }
      {
      name: 'CHROME_PORT'
      value: CHROME_PORT
      }
      {
      name: 'CHROME_URL'
      value: CHROME_URL
      }
      {
      name: 'DATABASE_URL'
      value: DATABASE_URL
    }
    {
      name: 'DOCKER_ENABLE_CI'
      value: DOCKER_ENABLE_CI
    }
    {
      name: 'DOCKER_REGISTRY_SERVER_PASSWORD'
      value: DOCKER_REGISTRY_SERVER_PASSWORD
    }
    {
       name: 'DOCKER_REGISTRY_SERVER_USERNAME'
      value: DOCKER_REGISTRY_SERVER_USERNAME
    }
    {
      name: 'DOCKER_REGISTRY_SERVER_URL'
      value: DOCKER_REGISTRY_SERVER_URL
    }
    {
      name: 'GITHUB_CALLBACK_URL'
      value: GITHUB_CALLBACK_URL
    }
    {
      name: 'GITHUB_CLIENT_ID'
      value: GITHUB_CLIENT_ID
    }
    {
      name: 'GITHUB_CLIENT_SECRET'
      value: GITHUB_CLIENT_SECRET
    }
    {
       name: 'GOOGLE_CALLBACK_URL'
      value: GOOGLE_CALLBACK_URL
    }
    {
      name: 'GOOGLE_CLIENT_ID'
      value: GOOGLE_CLIENT_ID
    }
    {
      name: 'GOOGLE_CLIENT_SECRET'
      value: GOOGLE_CLIENT_SECRET
    }
    {
      name: 'MICROSOFT_AUTHORIZATION_URL'
      value: MICROSOFT_AUTHORIZATION_URL
    }
    {
      name: 'MICROSOFT_CALLBACK_URL'
      value: MICROSOFT_CALLBACK_URL
    }
    {
      name: 'MICROSOFT_CLIENT_ID'
      value: MICROSOFT_CLIENT_ID
    }
    {
      name: 'MICROSOFT_CLIENT_SECRET'
      value: MICROSOFT_CLIENT_SECRET
    }
    {
      name: 'MICROSOFT_SCOPE'
      value: MICROSOFT_SCOPE
    }
    {
      name: 'MICROSOFT_TOKEN_URL'
      value: MICROSOFT_TOKEN_URL
    }
    {
      name: 'MICROSOFT_USER_INFO_URL'
      value: MICROSOFT_USER_INFO_URL
    }
    {
       name: 'OPENAI_API_KEY'
      value: OPENAI_API_KEY
    }
    {
      name: 'POSTGRES_DB'
      value: POSTGRES_DB
    }
    {
      name: 'POSTGRES_PASSWORD'
      value: POSTGRES_PASSWORD
    }
    {
      name: 'POSTGRES_USER'
      value: POSTGRES_USER
    }
    {
      name: 'POSTGRES_PORT'
      value: POSTGRES_PORT
    }
    {
      name: 'PUBLIC_URL'
      value: 'https://${sites.properties.defaultHostName}'
    }
    {
      name: 'REFRESH_TOKEN_SECRET'
      value: REFRESH_TOKEN_SECRET
    }
    {
      name: 'STORAGE_ACCESS_KEY'
      value: STORAGE_ACCESS_KEY
    }
    {
      name: 'STORAGE_BUCKET'
      value: STORAGE_BUCKET
    }
    {
      name: 'STORAGE_ENDPOINT'
      value: STORAGE_ENDPOINT
    }
    {
      name: 'STORAGE_PORT'
      value: STORAGE_PORT
    }
    {
      name: 'STORAGE_REGION'
      value: STORAGE_REGION
    }
    {
      name: 'STORAGE_SECRET_KEY'
      value: STORAGE_SECRET_KEY
    }
    {
      name: 'STORAGE_SKIP_BUCKET_CHECK'
      value: STORAGE_SKIP_BUCKET_CHECK
    }
    {
      name: 'STORAGE_URL'
      value: STORAGE_URL
    }
    {
      name: 'STORAGE_USE_SSL'
      value: STORAGE_USE_SSL
    }
    {
      name: 'WEBSITES_ENABLE_APP_SERVICE_STORAGE'
      value: WEBSITES_ENABLE_APP_SERVICE_STORAGE
    }
    {
      name: 'XDT_MicrosoftApplicationInsights_Mode'
      value: XDT_MicrosoftApplicationInsights_Mode
    }
    ]
    numberOfWorkers: 1
    defaultDocuments: [
      'Default.htm'
      'Default.html'
      'Default.asp'
      'index.htm'
      'index.html'
      'iisstart.htm'
      'default.aspx'
      'index.php'
      'hostingstart.html'
    ]
    netFrameworkVersion: 'v4.0'
    linuxFxVersion: 'DOCKER|mfknudsen/ez-cv:${dockerTag}'
    requestTracingEnabled: false
    remoteDebuggingEnabled: false
    remoteDebuggingVersion: 'VS2022'
    httpLoggingEnabled: true
    acrUseManagedIdentityCreds: false
    logsDirectorySizeLimit: 35
    detailedErrorLoggingEnabled: false
    publishingUsername: '$EzCV-container-webapp'
    scmType: 'None'
    use32BitWorkerProcess: true
    webSocketsEnabled: false
    alwaysOn: false
    managedPipelineMode: 'Integrated'
    virtualApplications: [
      {
        virtualPath: '/'
        physicalPath: 'site\\wwwroot'
        preloadEnabled: false
      }
    ]
    loadBalancing: 'LeastRequests'
    experiments: {
      rampUpRules: []
    }
    autoHealEnabled: false
    vnetRouteAllEnabled: false
    vnetPrivatePortsCount: 0
    publicNetworkAccess: 'Enabled'
    localMySqlEnabled: false
    ipSecurityRestrictions: [
      {
        ipAddress: 'Any'
        action: 'Allow'
        priority: 2147483647
        name: 'Allow all'
        description: 'Allow all access'
      }
    ]
    scmIpSecurityRestrictions: [
      {
        ipAddress: 'Any'
        action: 'Allow'
        priority: 2147483647
        name: 'Allow all'
        description: 'Allow all access'
      }
    ]
    scmIpSecurityRestrictionsUseMain: false
    http20Enabled: false
    minTlsVersion: '1.2'
    scmMinTlsVersion: '1.2'
    ftpsState: 'FtpsOnly'
    preWarmedInstanceCount: 0
    elasticWebAppScaleLimit: 0
    functionsRuntimeScaleMonitoringEnabled: false
    minimumElasticInstanceCount: 1
    azureStorageAccounts: {}
  }
}
