name: "Manual Deploy to Azure Web App - EzCV"

on:
  # Only run when manually triggered
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Needed for checking out code
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Create .env for testing
        run: |
          echo "VITE_POSTGRES_PORT=${{ secrets.VITE_POSTGRES_PORT }}" >> .env

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.13.1"

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install
          pnpm list

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      # Zip ONLY what's needed: dist/ + package.json + lockfile
      - name: Zip artifact for deployment
        run: |
          pnpm install --production
          zip -r release.zip \
            dist \
            package.json \
            package-lock.json \
            pnpm-lock.yaml 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write    # Required to request a JWT
      contents: read     # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "EzCV"
          package: release.zip
